name: Revengeshogi

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: PyInstaller Windows
      run: pyinstaller --onefile revengeshogi.py

    - uses: actions/upload-artifact@v2
      with:
        name: Revengeshogi
        path: dist/revengeshogi.exe
        
  linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-linux@main
      with:
        path: .

    - uses: actions/upload-artifact@v2
      with:
        name: Revengeshogi (Linux)
        path: dist/*       
